# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
