# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='image_url',
            new_name='icon_url',
        ),
    ]
